services:
  proxy:
    ports:
      - "${SERVER_EDGE_PROXY_NODE_BIND_IP:?SERVER_EDGE_PROXY_NODE_BIND_IP is required}:${SERVER_EDGE_PROXY_LOCAL_NODE_PORT:?SERVER_EDGE_PROXY_LOCAL_NODE_PORT is required}:${SERVER_EDGE_PROXY_LOCAL_NODE_PORT:?SERVER_EDGE_PROXY_LOCAL_NODE_PORT is required}/tcp"
      - "${SERVER_EDGE_PROXY_NODE_BIND_IP:?SERVER_EDGE_PROXY_NODE_BIND_IP is required}:${SERVER_EDGE_PROXY_LOCAL_NODE_PORT:?SERVER_EDGE_PROXY_LOCAL_NODE_PORT is required}:${SERVER_EDGE_PROXY_LOCAL_NODE_PORT:?SERVER_EDGE_PROXY_LOCAL_NODE_PORT is required}/udp"
