services:
  proxy:
    ports:
      - "${SERVER_EDGE_PROXY_EGRESS_BIND_IP:?SERVER_EDGE_PROXY_EGRESS_BIND_IP is required}:${SERVER_EDGE_PROXY_EGRESS_PORT:?SERVER_EDGE_PROXY_EGRESS_PORT is required}:${SERVER_EDGE_PROXY_EGRESS_PORT:?SERVER_EDGE_PROXY_EGRESS_PORT is required}/tcp"
      - "${SERVER_EDGE_PROXY_EGRESS_BIND_IP:?SERVER_EDGE_PROXY_EGRESS_BIND_IP is required}:${SERVER_EDGE_PROXY_EGRESS_PORT:?SERVER_EDGE_PROXY_EGRESS_PORT is required}:${SERVER_EDGE_PROXY_EGRESS_PORT:?SERVER_EDGE_PROXY_EGRESS_PORT is required}/udp"
